### ISSUE TITLE
[BUG] Crashes on startup(windows 11 clean install)

### ISSUE THREAD

**Issue by Jeremy2131** [radj307/volume-control#71]
### Version

5.2.5

### Actual Behaviour

App crashing on startup

### Expected Behaviour

App launches on startup

### Reproduction Steps

Launch the app

### Log

```shell
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

                             /// VOLUME CONTROL CRASH REPORT /// 19:21:43:442  [FATAL]   ///

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

HH:mm:ss:fff           === Log Initialized @ Wednesday, June 28, 2023 4:21:41 PM ===  { Filter: 30 (ALL_EXCEPT_DEBUG) }
19:21:41:275  [INFO]   The version number in the settings file was 0.0.0, settings will be upgraded to 5.2.5.
19:21:43:409  [ERROR]  An unhandled exception occurred!
                         Sender: 'System.Windows.Threading.Dispatcher' (System.Windows.Threading.Dispatcher)
                       {
                         'Message': 'The invocation of the constructor on type 'VolumeControl.Helpers.VolumeControlSettings' that matches the specified binding constraints threw an exception.'
                         'HResult': '-2146233087'
                         'Source': 'PresentationFramework'
                         'TargetSite': {
                           'Name': 'RewrapException'
                           'DeclaringType': 'System.Windows.Markup.XamlReader'
                           'Attributes': 'PrivateScope, Assembly, Static, HideBySig'
                           'CallingConvention': 'Standard'
                         }
                         'Data':{
                           'System.Object': ''
                         }
                         'StackTrace': {
                           [0] at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
                           [1] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                           [2] at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                           [3] at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                           [4] at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
                           [5] at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
                           [6] at System.Windows.Application.DoStartup()
                           [7] at System.Windows.Application.<.ctor>b__1_0(Object unused)
                           [8] at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
                           [9] at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
                         }
                         'InnerException': {
                           'Message': 'Process has exited, so the requested information is not available.'
                           'HResult': '-2146233079'
                           'Source': 'System.Diagnostics.Process'
                           'TargetSite': {
                             'Name': 'EnsureState'
                             'DeclaringType': 'System.Diagnostics.Process'
                             'Attributes': 'PrivateScope, Private, HideBySig'
                             'CallingConvention': 'Standard, HasThis'
                           }
                           'StackTrace': {
                             [0] at System.Diagnostics.Process.EnsureState(State state)
                             [1] at System.Diagnostics.Process.get_ProcessName()
                             [2] at VolumeControl.Audio.AudioSession..ctor(AudioSessionControl controller)
                             [3] at VolumeControl.Audio.AudioDevice.ReloadSessions()
                             [4] at VolumeControl.Audio.AudioDevice..ctor(MMDevice device)
                             [5] at VolumeControl.Audio.Collections.AudioDeviceCollection.CreateDeviceFromMMDevice(MMDevice mmDevice)
                             [6] at VolumeControl.Audio.Collections.AudioDeviceCollection.Reload(MMDeviceEnumerator enumerator)
                             [7] at VolumeControl.Audio.Collections.AudioDeviceCollection..ctor(AudioAPI api, DataFlow flow)
                             [8] at VolumeControl.Audio.AudioAPI..ctor()
                             [9] at VolumeControl.Helpers.VolumeControlSettings..ctor()
                             [10] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                           }
                         }
                       }
19:21:43:437  [FATAL]  App exited because of an unhandled exception!
                       {
                         'Message': 'The invocation of the constructor on type 'VolumeControl.Helpers.VolumeControlSettings' that matches the specified binding constraints threw an exception.'
                         'HResult': '-2146233087'
                         'Source': 'PresentationFramework'
                         'TargetSite': {
                           'Name': 'RewrapException'
                           'DeclaringType': 'System.Windows.Markup.XamlReader'
                           'Attributes': 'PrivateScope, Assembly, Static, HideBySig'
                           'CallingConvention': 'Standard'
                         }
                         'Data':{
                           'System.Object': ''
                         }
                         'StackTrace': {
                           [0] at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
                           [1] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                           [2] at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                           [3] at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                           [4] at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
                           [5] at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
                           [6] at System.Windows.Application.DoStartup()
                           [7] at System.Windows.Application.<.ctor>b__1_0(Object unused)
                           [8] at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
                           [9] at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
                           [10] at System.Windows.Threading.DispatcherOperation.InvokeImpl()
                           [11] at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
                           [12] at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
                           [13] at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                           [14] --- End of stack trace from previous location ---
                           [15] at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                           [16] at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                           [17] at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
                           [18] at System.Windows.Threading.DispatcherOperation.Invoke()
                           [19] at System.Windows.Threading.Dispatcher.ProcessQueue()
                           [20] at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
                           [21] at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
                           [22] at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
                           [23] at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
                           [24] at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
                           [25] at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
                           [26] at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
                           [27] at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
                           [28] at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
                           [29] at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
                           [30] at System.Windows.Threading.Dispatcher.Run()
                           [31] at System.Windows.Application.RunDispatcher(Object ignore)
                           [32] at System.Windows.Application.RunInternal(Window window)
                           [33] at System.Windows.Application.Run()
                           [34] at VolumeControl.Program.Main(String[] args)
                         }
                         'InnerException': {
                           'Message': 'Process has exited, so the requested information is not available.'
                           'HResult': '-2146233079'
                           'Source': 'System.Diagnostics.Process'
                           'TargetSite': {
                             'Name': 'EnsureState'
                             'DeclaringType': 'System.Diagnostics.Process'
                             'Attributes': 'PrivateScope, Private, HideBySig'
                             'CallingConvention': 'Standard, HasThis'
                           }
                           'StackTrace': {
                             [0] at System.Diagnostics.Process.EnsureState(State state)
                             [1] at System.Diagnostics.Process.get_ProcessName()
                             [2] at VolumeControl.Audio.AudioSession..ctor(AudioSessionControl controller)
                             [3] at VolumeControl.Audio.AudioDevice.ReloadSessions()
                             [4] at VolumeControl.Audio.AudioDevice..ctor(MMDevice device)
                             [5] at VolumeControl.Audio.Collections.AudioDeviceCollection.CreateDeviceFromMMDevice(MMDevice mmDevice)
                             [6] at VolumeControl.Audio.Collections.AudioDeviceCollection.Reload(MMDeviceEnumerator enumerator)
                             [7] at VolumeControl.Audio.Collections.AudioDeviceCollection..ctor(AudioAPI api, DataFlow flow)
                             [8] at VolumeControl.Audio.AudioAPI..ctor()
                             [9] at VolumeControl.Helpers.VolumeControlSettings..ctor()
                             [10] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                           }
                         }
                       }
```

**Comment by Jeremy2131** [comment]
I restarted the PC and the problem was solved, I will leave this bug here, maybe it will help you to inspect it in the future.

**Comment by radj307** [comment]
Log indicates a problem occurred when getting the name of a process (while reloading the list of `AudioSession` instances).

**Comment by radj307** [comment]
Cannot replicate on Windows 11 Home 22H2 OS Build 22621.1702 virtual machine.

**Comment by Cmscrew** [comment]
I am also having this same issue, when trying to start the exe it crashes and creates a crash log. I've never used this program before but im really excited to as this is exactly what im looking for.

i did also try downloading the prerelease 6 and that does not crash when i start the exe, however it is completely invisible and i cannot interact w the program, even after click on it in system tray and selecting bring to front. i see it running in task bar. but like i said that is for the prerelease. im more worried about 5.2.5 not launching at all. Hoping to get some quick help!

**Comment by Jeremy2131** [comment]
It was fixed by itself somehow plus I had to reinstall windows so it works

**Comment by radj307** [comment]
@Cmscrew 
Can you provide your specific Windows version?

To get it, open the start menu and enter `winver`.  
![image](https://github.com/radj307/volume-control/assets/1927798/27ff3be1-7b35-4de3-a3ef-70011de5dec7)
